complexity:
  LongMethod:
    threshold: 300
  TooManyFunctions:
    thresholdInFiles: 50
    thresholdInClasses: 50
    thresholdInInterfaces: 50

style:
  MaxLineLength:
    maxLineLength: 200
  WildcardImport:
    active: false