complexity:
  ComplexMethod:
    threshold: 30
  LargeClass:
    excludes: ['**/test/**']
  LongMethod:
    threshold: 300
  TooManyFunctions:
    thresholdInFiles: 50
    thresholdInClasses: 50
    thresholdInInterfaces: 50
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 15

style:
  MaxLineLength:
    maxLineLength: 200
  WildcardImport:
    active: false