complexity:
  ComplexMethod:
    threshold: 40
  LargeClass:
    excludes: ['**/test/**']
  LongMethod:
    threshold: 100
    excludes: ['**/test/**']
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 15
    excludes: ['**/com/ecwid/apiclient/v3/ApiClient.kt']
  NestedBlockDepth:
    excludes: ['**/test/**']
  TooManyFunctions:
    thresholdInFiles: 50
    thresholdInClasses: 50
    thresholdInInterfaces: 50

naming:
  EnumNaming:
    active: false # We need to fix all enums before enabling this inspection

style:
  MaxLineLength:
    active: false # Will user ktlint formatting.MaximumLineLength inspection instead
  ThrowsCount:
    max: 5
  ReturnCount:
    max: 5
  UnnecessaryAbstractClass:
    excludes: ['**/test/**']
  WildcardImport:
    active: false

# ktlint rules
formatting:
  MaximumLineLength:
    maxLineLength: 180
  # Initially enabled
  NoBlankLineBeforeRbrace:
    active: false
  NoConsecutiveBlankLines:
    active: false
  NoWildcardImports:
    active: false
  ParameterListWrapping:
    active: false # Will be enabled after ktlint will have support of indent_style = tab
  # Initially disabled
  ArgumentListWrapping:
    active: false # Will be enabled after ktlint will have support of indent_style = tab
  Indentation:
    active: false # Will be enabled after ktlint will have support of indent_style = tab
