package com.ecwid.apiclient.v3.exception

const val EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS"
const val INVALID_REGISTER_EMAIL = "INVALID_REGISTER_EMAIL"
const val INVALID_REGISTER_NAME = "INVALID_REGISTER_NAME"
