name: On pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout full repository history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Upload dev snapshot to Maven Central with Gradle
      run: gradle devSnapshot
      env:
        STORE_ID: ${{ secrets.STORE_ID }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        API_HOST: ${{ secrets.API_HOST }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-results
        path: /home/runner/work/ecwid-java-api-client/ecwid-java-api-client/build/reports/tests/test/*
