name: On pull request

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout full repository history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build, run tests and upload dev snapshot to Maven Central with Gradle
      run: ./gradlew devSnapshot printDevSnapshotReleaseNode
      env:
        STORE_ID: ${{ secrets.STORE_ID }}
        API_TOKEN: ${{ secrets.API_TOKEN }}
        API_HOST: ${{ secrets.API_HOST }}
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}

    - name: Upload artifacts with checks results
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: check-results
        path: |
          ${{ github.workspace }}/build/reports/tests/test/*
          ${{ github.workspace }}/build/reports/detekt/detekt.html

    - name: Upload static analysis results
      uses: github/codeql-action/upload-sarif@v1
      if: always()
      with:
        sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif