name: On push to master

on:
  push:
    branches:
      - master

concurrency: push-to-master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout full repository history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github

      - name: Build, upload release version to Maven Central and create git release tag with Gradle
        run: ./gradlew detekt final closeAndReleaseStagingRepository printFinalReleaseNote
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
          GRGIT_PASS: ${{ secrets.GRGIT_PASS }}

      - name: Upload static analysis results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: ${{ github.workspace }}/build/reports/detekt/detekt.sarif
          category: "Detekt Scanning"
