name: On push to master

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout full repository history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        server-id: github
        settings-path:

    - name: Build, upload release version to Maven Central and create git release tag with Gradle
      run: gradle final closeAndReleaseRepository --info
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GRGIT_USER: ${{ secrets.GRGIT_USER }}
        GRGIT_PASS: ${{ secrets.GRGIT_PASS }}
